### ISSUE TITLE
Bug in v1.1.0 : `direction` in subgraph generate TypeError: Cannot read properties of null (reading 'namespace')

### ISSUE THREAD

**Issue by pleyo** [aloisklink/remark-mermaid-dataurl#20]
Hi,

I've updated the library from 1.0.2 to 1.1.0 and an issue appeared when I build my code.

## Expected Behavior
client compiled successfully

## Current Behavior
TypeError: Cannot read properties of null (reading 'namespace')
    at async Promise.all (index 0)
client compiled with 1 error

## Possible Solution
After investigation and some testing, I managed to make it works by removing the `direction` line under subgraph.

## Steps to Reproduce
1. project running on remark-mermaid-dataurl v1.1.0 & docusaurus v2
2. In mermaid md tag :
```
flowchart TB
subgraph subDummy
    direction TB
    foo[foo] -. can be .-> bar
end
```

**Comment by aloisklink** [comment]
Hi @pleyo, thanks for reporting this issue!

It should be fixed in [remark-mermaid-dataurl 1.1.1](https://github.com/aloisklink/remark-mermaid-dataurl/releases/tag/v1.1.1). You may also need to run `npm upgrade remark-mermaid-dataurl @mermaid-js/mermaid-cli` to make sure that mermaid-cli is at least v8.10.2.

In version 1.1.0, I explicitly limited `@mermaid-js/mermaid-cli` version to be `<=8.10.1`,
since that upgrades to [puppeteer v10.0.0](https://github.com/mermaid-js/mermaid-cli/pull/128), which drops Node v10 support.

Unfortunately, that version of `mermaid-cli` uses Mermaid v8.10.1, which doesn't support the `direction` option in `flowchart` `subgraphs` (that was only added in [Mermaid 8.10.2](https://github.com/mermaid-js/mermaid/releases/tag/untagged-f83ec2a9deaf6677e0c7)).

However, it looks like although Node v10 is not officially supported by mermaid-cli 8.10.2+, it still actually works, so I've converted `@mermaid-js/mermaid-cli` to be `^8.9.2`, like it was previously!
