### ISSUE TITLE
gitGraph cut off

### ISSUE THREAD

**Issue by ghost** [aloisklink/remark-mermaid-dataurl#7]
![image](https://user-images.githubusercontent.com/50320942/116692023-ffc4d400-a9bb-11eb-8887-5e6ab4cc3931.png)

I know `gitGraph` is experimental. Yet still I wonder why it does not work.
If you open the image in a new tab, it works:

![image](https://user-images.githubusercontent.com/50320942/116692080-18cd8500-a9bc-11eb-8e15-1a53cc194adb.png)

It from somewhere thinks it must be 300px.

I use it with  [docusaurus.io](https://docusaurus.io/).

Also, how could I pass `mermaidCli` options?

This does not seem to work:

```js
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
          // Please change this to your repo.
          editUrl:
            'https://github.tools.sap/xeeti/docs/edit/main/',
          remarkPlugins: [
            [remarkMermaid, {gitGraphConfig: {width: '100%'}}],
            simplePlantUML
          ],
        },
```

Thank you 🤝

**Comment by aloisklink** [comment]
Hi, sorry for fixing this quite late!

Unfortunately, setting `gitGraphConfig` wouldn't work for me. In my testing, it looks like if an SVG has width 100%, your browser will just always default to width 300px when including the SVG.

Because of this, since v1.1.0, `remark-mermaid-dataurl`, now uses [svgdom](https://github.com/svgdotjs/svgdom) to find the width of an SVG in pixels, then sets the width to that. It seems to work now! See below:

![test/__image_snapshots__/index-test-js-test-markdown-files-should-render-git-graphs-visually-1-snap.png](https://raw.githubusercontent.com/aloisklink/remark-mermaid-dataurl/v1.1.0/test/__image_snapshots__/index-test-js-test-markdown-files-should-render-git-graphs-visually-1-snap.png)
