### ISSUE TITLE
Timout in generating graph

### ISSUE THREAD

**Issue by pilmrc** [aloisklink/remark-mermaid-dataurl#9]
Hi,
I'm using this plugin, and when rendering mermaid from a sing markdown file using docusaurus, all is working as expected.
But when docusaurus processing the entire website, I'm getting the following error:

```
(node:20688) UnhandledPromiseRejectionWarning: TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r901912 is guaranteed to work.
    at Timeout.onTimeout (D:\my-website\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:208:20)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)

Docusaurus: 2.0.0 beta9
remark-mermaid-dataurl 1.0.2
```

Is there any parameter to setup the timeout to the open chromium browser?

**Comment by aloisklink** [comment]
Hi, sorry for the late reply,

I've added the functionality of setting a puppeteer config file in `v1.1.0`.

If you try passing the following options in your `docusaurus.config.js`, it should increase the puppeteer launch timeout to 60 seconds.

```js
module.exports = {
  // ...
  presets: [
    [
      "@docusaurus/preset-classic",
      {
        docs: {
          // ...
          remarkPlugins: [
            require("remark-mermaid-dataurl"),
            {
              mermaidCli: {
                puppeteerConfigFile: {
                // see options at https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#puppeteerlaunchoptions
                timeout: 60000, // change default puppeteer launch timeout to 60s
                },
              },
            }
          ],
        },
      },
    ],
  ],
};
```

You might also be able to use `firefox` or a different chrome version, and see if that helps.

Alternatively, instead of building all the mermaid diagrams when running `docusaurus build`, you could instead render all your mermaid diagrams using client-side rendering on demand, using the plugin [mdx-mermaid](https://github.com/sjwall/mdx-mermaid).
